from .errors import EntryCreatedError as EntryCreatedError, OperationCompletionError as OperationCompletionError, ResponseError as ResponseError
from logging import Logger
from typing import Dict, List, Text, Union

from requests import Response

logger: Logger

def generate_uuid() -> str: ...
def convert_string(value: str) -> str: ...
def dict_to_payload(dictionary: Dict) -> List[Dict]: ...
def gen_attributes(rp_attributes: List) -> List[Dict]: ...
def get_launch_sys_attrs()-> Dict[Text]: ...
def get_package_version(package_name:Text) -> Text: ...
def uri_join(*uri_parts: str) -> str: ...
def get_id(response: Response) -> str: ...
def get_msg(response: Response) -> Dict: ...
def get_data(response: Response) -> Dict: ...
def get_json(response: Response) -> Dict: ...
def get_error_messages(data: Dict) -> List: ...
def verify_value_length(
        attributes: Union[List[Dict], None]) -> Union[List[Dict], None]: ...

def timestamp() -> str: ...
