from requests import Response
from typing import Dict, Iterable, Optional, Text, Tuple

class RPMessage:
    error_code: Text = ...
    message: Text = ...
    def __init__(self, data: Dict) -> None: ...
    @property
    def is_empty(self) -> bool: ...

class RPResponse:
    _data: Dict = ...
    _resp: Response = ...
    def __init__(self, data: Response) -> None: ...
    def _get_json(self, data: Response) -> Dict: ...
    def _iter_messages(self) -> Iterable[RPMessage]: ...
    @property
    def id(self) -> Optional[Text]: ...
    @property
    def is_success(self) -> bool: ...
    @property
    def json(self) -> Dict: ...
    @property
    def message(self) -> Text: ...
    @property
    def messages(self) -> Tuple[RPMessage]: ...
