#  Copyright (c) 2022 EPAM Systems
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License

from requests import Response
from typing import Dict, Iterable, Optional, Text, Tuple

class RPMessage:
    error_code: Text = ...
    message: Text = ...
    def __init__(self, data: Dict) -> None: ...
    @property
    def is_empty(self) -> bool: ...

class RPResponse:
    _data: Dict = ...
    _resp: Response = ...
    def __init__(self, data: Response) -> None: ...
    def _get_json(self, data: Response) -> Dict: ...
    def _iter_messages(self) -> Iterable[RPMessage]: ...
    @property
    def id(self) -> Optional[Text]: ...
    @property
    def is_success(self) -> bool: ...
    @property
    def json(self) -> Dict: ...
    @property
    def message(self) -> Text: ...
    @property
    def messages(self) -> Tuple[RPMessage]: ...
