from typing import Any, Optional, Dict, List

from requests import Session

from reportportal_client.core.rp_file import RPFile
from reportportal_client.items.rp_test_items.rp_base_test_item import \
    RPBaseTestItem


class TestManager:
    rp_url: str = ...
    session: Session = ...
    api_version: str = ...
    launch_id: str = ...
    project_name: str = ...
    __storage: List = ...

    def __init__(self, rp_url: str, session: Session, api_version: str,
                 launch_id: str, project_name: str) -> None: ...

    def start_test_item(self, name: str, start_time: str, item_type: str,
                        description: Optional[str] = ...,
                        attributes: Optional[Dict] = ...,
                        parameters: Optional[Dict] = ...,
                        parent_uuid: Optional[str] = ...,
                        has_stats: bool = ..., **kwargs: Any) -> str: ...

    def update_test_item(self, item_uuid: str, attributes: Optional[Dict] = ...,
                         description: Optional[str] = ...,
                         **kwargs: Any) -> None: ...

    def finish_test_item(self, item_uuid: str, end_time: str, status: str,
                         issue: Optional[str] = ...,
                         attributes: Optional[Dict] = ...,
                         **kwargs: Any) -> None: ...

    def remove_test_item(self, item_uuid: str) -> None: ...

    def log(self, time: str, message: Optional[str] = ...,
            level: Optional[str] = ..., attachment: Optional[RPFile] = ...,
            item_id: Optional[str] = ...) -> str: ...

    def get_test_item(self, item_uuid: str) -> RPBaseTestItem: ...

    def get_storage(self) -> List: ...

    def _find_item(self, item_uuid: str, storage: List) -> RPBaseTestItem: ...
